########################################################################################################################
# Custom Profile
########################################################################################################################
[gwrite.fast-plot]
unit = "mm"
document_start = """
G90       ; absolute coordinates
G21       ; mm units
G17       ; xy plane
G00 Z1    ; pen up"""

layer_start = "(Start Layer)\n"
line_start = "(Start Layer)\n"

segment_first = """(Start Segment)
G00 Z1 (pen up)
G00 X{x:.4f} Y{y:.4f} (travel)
G00 Z0(pen down)\n"""

segment = """G00 X{x:.4f} Y{y:.4f}\n"""

line_end = """(Line End)
G00 Z1 (pen up)"""

document_end = """(Document End)
G00 Z1 (pen up)
G00 X0.0 Y0.0
M2"""

invert_y = false
vertical_flip = true

info= "FAST PLOT. All G00 movements. Gcode ready to print. File created succesfully."

########################################################################################################################
# Custom Profile test
########################################################################################################################
[gwrite.medium-plot]
unit = "mm"
document_start = """
G90       ; absolute coordinates
G21       ; mm units
G17       ; xy plane
G00 Z1    ; pen up"""

layer_start = "(Start Layer)\n"
line_start = "(Start Layer)\n"

segment_first = """(Start Segment)
G00 Z1 (pen up)
G01 X{x:.4f} Y{y:.4f} F5000 (travel)
G04 P0.5 (pause)
G00 Z0(pen down)
"""

segment = """G01 X{x:.4f} Y{y:.4f} F1000\n"""

line_end = """(Line End)
G00 Z1 (pen up)
"""

document_end = """(Document End)
G00 Z1 (pen up)
G00 X0.0 Y0.0
M2"""

invert_y = false
vertical_flip = true

info= "MEDIUM PLOT. F1000 moves, with 0.5 second dwell. Gcode ready to print. File created succesfully."

########################################################################################################################
[gwrite.slow-plot]
unit = "mm"
document_start = """
G90       ; absolute coordinates
G21       ; mm units
G17       ; xy plane
G00 Z1    ; pen up"""

layer_start = "(Start Layer)\n"
line_start = "(Start Layer)\n"

segment_first = """(Start Segment)
G00 Z1 (pen up)
G01 X{x:.4f} Y{y:.4f} F500 (travel at F-speed)
G00 Z0(pen down)
G04 P0.5 (pause 500 ms)\n"""

segment = """G01 X{x:.4f} Y{y:.4f} F500\n"""

line_end = """(Line End)
G04 P0.1 (pause 100 ms)
G00 Z1 (pen up)"""

document_end = """(Document End)
G00 Z1 (pen up)
G00 X0.0 Y0.0
M2"""

invert_y = false
vertical_flip = true

info= "SLOW PLOT. All G01 F500 draw movements. Gcode ready to print. File created succesfully."
