########################################################################################################################
# Custom Profile
########################################################################################################################
[gwrite.fast-plot]
unit = "mm"
document_start = """
G90       ; absolute coordinates
G21       ; mm units
G17       ; xy plane
G00 Z1    ; pen up"""

layer_start = "(Start Layer)\n"
line_start = "(Start Layer)\n"

segment_first = """(Start Segment)
G00 Z1 (pen up)
G00 X{x:.4f} Y{y:.4f} (travel)
G00 Z0(pen down)\n"""

segment = """G00 X{x:.4f} Y{y:.4f}\n"""

line_end = """(Line End)
G00 Z1 (pen up)"""

document_end = """(Document End)
G00 Z1 (pen up)
G00 X0.0 Y0.0
M2"""

invert_y = true

info= "FAST PLOT. All G00 movements. Gcode ready to print. File created succesfully."

########################################################################################################################
[gwrite.medium-plot]
unit = "mm"
document_start = """
G90       ; absolute coordinates
G21       ; mm units
G17       ; xy plane
G00 Z1    ; pen up"""

layer_start = "(Start Layer)\n"
line_start = "(Start Layer)\n"

segment_first = """(Start Segment)
G00 Z1 (pen up)
G01 X{x:.4f} Y{y:.4f} F5000 (travel at F-speed)
G00 Z0(pen down)\n"""

segment = """G01 X{x:.4f} Y{y:.4f} F5000\n"""

line_end = """(Line End)
G00 Z1 (pen up)"""

document_end = """(Document End)
G00 Z1 (pen up)
G00 X0.0 Y0.0
M2"""

invert_y = true

info= "MEDIUM PLOT. All G01 F5000 draw movements. Gcode ready to print. File created succesfully."

########################################################################################################################
[gwrite.slow-plot]
unit = "mm"
document_start = """
G90       ; absolute coordinates
G21       ; mm units
G17       ; xy plane
G00 Z1    ; pen up"""

layer_start = "(Start Layer)\n"
line_start = "(Start Layer)\n"

segment_first = """(Start Segment)
G00 Z1 (pen up)
G01 X{x:.4f} Y{y:.4f} F1000 (travel at F-speed)
G00 Z0(pen down)
G04 P200 (pause 200 ms)\n"""

segment = """G01 X{x:.4f} Y{y:.4f} F1000\n"""

line_end = """(Line End)
G04 P200 (pause 200 ms)
G00 Z1 (pen up)"""

document_end = """(Document End)
G00 Z1 (pen up)
G00 X0.0 Y0.0
M2"""

invert_y = true

info= "SLOW PLOT. All G01 F1000 draw movements. Gcode ready to print. File created succesfully."