########################################################################################################################
# Custom Profile
########################################################################################################################
[gwrite.thrly]
unit = "mm"
document_start = "G21\nG17\nG90\n"
layer_start = "(Start Layer)\n"
line_start = "(Start Block)\n"
segment_first = """G00 Z1 (pen up)
G00 X{x:.4f} Y{y:.4f} (travel)
G1 Z0 F6000\n (pen down)
"""
segment = """G01 X{x:.4f} Y{y:.4f} F10000\n"""
line_end = """G00 Z 5.0000
M5 S0
G4 P0.5\n"""
document_end = """M5
G00 X0.0000 Y0.0000
M2"""
invert_y = true
info= "Profile settings stored in c:_users_USER in .vpype.toml\nInverted across the y-axis. Gcode ready to print. File created succesfully."
